TRUNCATE TABLE amanah_deal;
TRUNCATE TABLE bids;
TRUNCATE TABLE bid_member;
TRUNCATE TABLE deposit;
UPDATE dinarpal_account SET da_gold_rahnu_gram = 0, da_gold_rahnu_money = 0, da_gold_balance = 0, da_gold_reserved = 0, da_silver_rahnu_gram = 0, da_silver_rahnu_money = 0, da_silver_balance = 0, da_silver_reserved = 0, da_point_balance = 0;
TRUNCATE TABLE dinarpal_document;
TRUNCATE TABLE dinarpal_transaction;
TRUNCATE TABLE item_storage;
TRUNCATE TABLE item_storage_child;
TRUNCATE TABLE pawn;
TRUNCATE TABLE pawn_child;
TRUNCATE TABLE pawn_child_child;
TRUNCATE TABLE sellbuy_board;
TRUNCATE TABLE souq;
TRUNCATE TABLE souq_adc;
TRUNCATE TABLE souq_child;
TRUNCATE TABLE souq_child_child;
TRUNCATE TABLE transaction;
TRUNCATE TABLE used_item;
TRUNCATE TABLE button_api;
TRUNCATE TABLE merchant;
TRUNCATE TABLE keep;
TRUNCATE TABLE keep_child;
TRUNCATE TABLE send_payment_gram;
TRUNCATE TABLE geneology_aff_child;
TRUNCATE TABLE liquid_item;
TRUNCATE TABLE withdrawal_gram;
TRUNCATE TABLE withdrawal_gram_child;
TRUNCATE TABLE banks_members;
TRUNCATE TABLE blast_email;
TRUNCATE TABLE chat_board;
TRUNCATE TABLE exchange_gram;
TRUNCATE TABLE exchange_gram_child;
UPDATE vault SET vt_id = 3, me_id = 1, me_id_lock = 0;
DELETE FROM members WHERE me_id > 5;
UPDATE members SET me_activation_status = 2;
DELETE FROM geneology_aff WHERE ga_id > 7;
DELETE FROM bene_info_waris WHERE biw_id > 7;
DELETE FROM vault WHERE v_id > 100;
ALTER TABLE vault AUTO_INCREMENT = 101;
ALTER TABLE members AUTO_INCREMENT = 6;
ALTER TABLE geneology_aff AUTO_INCREMENT = 8;
ALTER TABLE bene_info_waris AUTO_INCREMENT = 8;
DELETE FROM dinarpal_account WHERE da_id > 3;
ALTER TABLE dinarpal_account AUTO_INCREMENT = 4;
DELETE FROM emails WHERE em_id > 5;
ALTER TABLE emails AUTO_INCREMENT = 6;
UPDATE emails SET em_status = 2;
DELETE FROM dinarpal_funds WHERE me_id <> 1;
UPDATE dinarpal_funds SET df_balance = 0;
