TRUNCATE TABLE amanah_deal;
TRUNCATE TABLE bids;
TRUNCATE TABLE bid_member;
TRUNCATE TABLE deposit;
UPDATE dinarpal_account SET da_gold_rahnu_gram = 0, da_gold_rahnu_money = 0, da_gold_balance = 200000, da_gold_reserved = 0, da_silver_rahnu_gram = 0, da_silver_rahnu_money = 0, da_silver_balance = 200000, da_silver_reserved = 0, da_point_balance = 0;
TRUNCATE TABLE dinarpal_transaction;
TRUNCATE TABLE item_storage;
TRUNCATE TABLE item_storage_child;
TRUNCATE TABLE pawn;
TRUNCATE TABLE pawn_child;
TRUNCATE TABLE pawn_child_child;
TRUNCATE TABLE sellbuy_board;
TRUNCATE TABLE souq;
TRUNCATE TABLE souq_adc;
TRUNCATE TABLE souq_child;
TRUNCATE TABLE souq_child_child;
TRUNCATE TABLE transaction;
TRUNCATE TABLE used_item;
TRUNCATE TABLE button_api;
TRUNCATE TABLE merchant;
DELETE FROM members WHERE me_id > 17;
ALTER TABLE members AUTO_INCREMENT = 20;
DELETE FROM dinarpal_account WHERE me_id > 17;
ALTER TABLE dinarpal_account AUTO_INCREMENT = 20;
DELETE FROM emails WHERE em_id > 18;
ALTER TABLE emails AUTO_INCREMENT = 20;