TRUNCATE TABLE amanah_deal;
TRUNCATE TABLE bids;
TRUNCATE TABLE bid_member;
TRUNCATE TABLE deposit;
UPDATE dinarpal_account SET da_gold_rahnu_gram = 0, da_gold_rahnu_money = 0, da_gold_balance = 0, da_gold_reserved = 0, da_silver_rahnu_gram = 0, da_silver_rahnu_money = 0, da_silver_balance = 0, da_silver_reserved = 0, da_point_balance = 0;
TRUNCATE TABLE dinarpal_transaction;
TRUNCATE TABLE item_storage;
TRUNCATE TABLE item_storage_child;
TRUNCATE TABLE pawn;
TRUNCATE TABLE pawn_child;
TRUNCATE TABLE pawn_child_child;
TRUNCATE TABLE sellbuy_board;
TRUNCATE TABLE souq;
TRUNCATE TABLE souq_adc;
TRUNCATE TABLE souq_child;
TRUNCATE TABLE souq_child_child;
TRUNCATE TABLE transaction;
TRUNCATE TABLE used_item;
TRUNCATE TABLE button_api;
TRUNCATE TABLE merchant;
TRUNCATE TABLE keep;
TRUNCATE TABLE keep_child;
TRUNCATE TABLE send_payment_gram;
TRUNCATE TABLE geneology_aff_child;
UPDATE vault SET vt_id = 3, me_id = 1;
DELETE FROM members WHERE me_id > 17;
DELETE FROM geneology_aff WHERE ga_id > 7;
DELETE FROM bene_info_waris WHERE biw_id > 7;
DELETE FROM vault WHERE v_id > 17286;
ALTER TABLE members AUTO_INCREMENT = 20;
ALTER TABLE geneology_aff AUTO_INCREMENT = 8;
ALTER TABLE bene_info_waris AUTO_INCREMENT = 8;
DELETE FROM dinarpal_account WHERE me_id > 17;
ALTER TABLE dinarpal_account AUTO_INCREMENT = 20;
DELETE FROM emails WHERE em_id > 18;
ALTER TABLE emails AUTO_INCREMENT = 20;